setwd("/Users/keren/Desktop/covid")
library("seqinr")
library("ape")
library("DECIPHER")
library("TreeSearch")
library("phangorn")
library("msa")
seqs = read.fasta(file="sequences.fasta.txt")
seqs2 = readDNAStringSet(file="full_sequences.fasta")
tree = read.nexus("tree.nex.txt")
tree2 = read.tree("tree.nex")
# aligned.dna = AlignSeqs(seqs2)
tree3 = read.tree("tree.nwk")
result = Fitch(tree3)

tmp = read.fasta(file = "aligned.dna")
dataset = phyDat(aligned.dna)


setwd("/Users/keren/Desktop/covid")
library("seqinr")
library("ape")
library("DECIPHER")
library("TreeSearch")
library("phangorn")
library("msa")
seqs = read.fasta(file="sequences.fasta.txt")
seqs2 = readDNAStringSet(file="full_sequences.fasta")
aligned.seqs = msa(seqs2)
tree = read.nexus("tree.nex.txt")
tree2 = read.tree("tree.nex")
# aligned.dna = AlignSeqs(seqs2)
tree3 = read.tree("tree.nwk")
result = Fitch(tree3)

tmp = read.fasta(file = "aligned.dna.txt")
dataset = phyDat(aligned.dna)
# 
# if (!requireNamespace("BiocManager", quietly=TRUE))
#   install.packages("BiocManager")
# BiocManager::install("msa")
# system.file("tex", "texshade.sty", package="msa")